apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: placement-pro

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: placement-pro
  app.kubernetes.io/part-of: enterprise-placement-system
  app.kubernetes.io/managed-by: kustomize
