apiVersion: v1
kind: Secret
metadata:
  name: placement-secrets
  namespace: placement-pro
type: Opaque
stringData:
  POSTGRES_USER: "placement_admin"
  POSTGRES_PASSWORD: "PlacementSecurePass2026!Prod"
  JWT_SECRET_KEY: "k8s-prod-enterprise-jwt-key-2026-spvm3-placement"
